name: flutter_jules
description: A basic Flutter client for the Jules API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  dartobjectutils: ^0.1.1
  shared_preferences: ^2.5.4
  google_sign_in: ^6.2.1
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/default_bookmarks.json
