name: flutter_jules
description: Arrans Flutter based jules client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  dartobjectutils: ^0.1.1
  shared_preferences: ^2.5.4
  google_sign_in: ^6.2.1
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.4.0
  flutter_local_notifications: ^17.2.1
  tray_manager: ^0.2.3
  window_manager: ^0.3.8
  collection: ^1.18.0
  desktop_multi_window: ^0.2.0

  duration: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.13.1
  fake_async: ^1.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#0175c2"
    theme_color: "#0175c2"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/default_bookmarks.json
    - assets/icon/app_icon.png
